### ISSUE TITLE
Feature Selection Methods

### ISSUE THREAD

**Issue by deannagould** [learn-co-curriculum/dsc-feature-selection-methods#2]
## Link to Canvas

https://learning.flatironschool.com/courses/5600/assignments/200741?module_item_id=456043

## Issue Subtype

- [x ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
# Create dummy variable for sex
ohe = OneHotEncoder(drop='first', sparse_output=False)
train_female = ohe.fit_transform(X_train[['SEX']]).flatten()
test_female = ohe.transform(X_test[['SEX']]).flatten()
```

### Concern

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse_output'
## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Thanks for opening this issue @deannagould :wave:. Running this locally on the `learn-env` environment requires you use a deprecated version of the code. If you run 

`ohe = OneHotEncoder(drop='first', sparse=False)`

It will work in the `learn-env`. On Saturn Cloud the notebook works with the updated keyword argument. I am going to close this issue at this time. I hope this helps!
